name: 'docker-compose'
description: 'Run docker-compose command'
author: 'Svetlin Ralchev'

# Define your inputs here.
inputs:
  docker-compose-path:
    description: 'The path to the docker-compose.yml'
    default: 'docker-compose.yml'
    required: true
  docker-compose-profile:
    description: 'The docker compose profile'
    default: '${{ github.job }}'
    required: true

runs:
  using: node20
  main: dist/index.main.js
  post: dist/index.post.js
